package com.runetide.common.domain;

import com.fasterxml.jackson.annotation.JsonValue;

public enum BiomeType implements IndexedEnum {
    TUNDRA(0), TAIGA(1), MONTANE_GRASSLANDS(2), MONTANE_SHRUBLANDS(3), CONIFEROUS_FORESTS(4),
    MIXED_FORESTS(5), DECIDUOUS_FORESTS(6), GRASSLANDS(7), SAVANNAS(8), SHRUBLANDS(9),
    MOIST_BROADLEAF_FORESTS(10), DRY_BROADLEAF_FORESTS(11), MEDITERRANEAN_FORESTS(12),
    MEDITERRANEAN_WOODLANDS(13), MEDITERRANEAN_SCRUB(14), DESERT(15), XERIC_SHRUBLANDS(16),
    FLOODED_GRASSLANDS(17), FLOODED_SAVANNAS(18), RIPARIAN(19), WETLAND(20), MANGROVE(21), POND(22),
    LITTORAL(23), INTERTIDAL(24), KELP_FORESTS(25), CORAL_REEFS(26), NERITIC_ZONE(27),
    PELAGIC_ZONE(28), BENTHIC_ZONE(29), HYDROTHERMAL_VENTS(30), COLD_SEEPS(31), DEMERSAL_ZONE(32),
    ENDOLITHIC_ZONE(33);

    private final int id;

    BiomeType(int id) {
        this.id = id;
    }

    @Override
    @JsonValue
    public int toValue() {
        return id;
    }
}
