package com.runetide.common.domain;

public enum BiomeType {
    TUNDRA, TAIGA, MONTANE_GRASSLANDS, MONTANE_SHRUBLANDS, CONIFEROUS_FORESTS, MIXED_FORESTS,
    DECIDUOUS_FORESTS, GRASSLANDS, SAVANNAS, SHRUBLANDS, MOIST_BROADLEAF_FORESTS, DRY_BROADLEAF_FORESTS,
    MEDITERRANEAN_FORESTS, MEDITERRANEAN_WOODLANDS, MEDITERRANEAN_SCRUB, DESERT, XERIC_SHRUBLANDS, FLOODED_GRASSLANDS,
    FLOODED_SAVANNAS, RIPARIAN, WETLAND, MANGROVE, POND, LITTORAL, INTERTIDAL, KELP_FORESTS, CORAL_REEFS, NERITIC_ZONE,
    PELAGIC_ZONE, BENTHIC_ZONE, HYDROTHERMAL_VENTS, COLD_SEEPS, DEMERSAL_ZONE, ENDOLITHIC_ZONE
}
