package com.runetide.common.domain;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.Map;

public enum BlockType {
    AIR(0, 0, 0, true, null, null),

    // Rocks
/*    TALC(1, 20, 0, false, ItemType.BROKEN_TALC, ItemType.WOODEN_PICKAXES),
    GYPSUM(2, 80, 0, false, ItemType.BROKEN_GYPSUM, ItemType.STONE_PICKAXES),
    CALCITE(3, 100, 0, false, ItemType.BROKEN_CALCITE, ItemType.STONE_PICKAXES),
    LIMESTONE(4, 140, 0, false, ItemType.BROKEN_LIMESTONE, ItemType.STONE_PICKAXES),
    SANDSTONE(5, 180, 0, false, ItemType.BROKEN_SANDSTONE, ItemType.IRON_PICKAXES),
    MARBLE(6, 200, 0, false, ItemType.BROKEN_MARBLE, ItemType.IRON_PICKAXES),
    APATITE(7, 240, 0, false, ItemType.BROKEN_APATITE, ItemType.IRON_PICKAXES),
    BASALT(8, 280, 0, false, ItemType.BROKEN_BASALT, ItemType.QUARTZ_PICKAXES),
    OBSIDIAN(9, 300, 0, false, ItemType.BROKEN_OBSIDIAN, ItemType.QUARTZ_PICKAXES),
    FELDSPAR(10, 350, 0, false, ItemType.BROKEN_FELDSPAR, ItemType.QUARTZ_PICKAXES),
    PUMICE(11, 400, 0, false, ItemType.BROKEN_PUMICE, ItemType.JADE_PICKAXES),
    GRANITE(12, 500, 0, false, ItemType.BROKEN_GRANITE, ItemType.JADE_PICKAXES),
    RHYOLITE(13, 750, 0, false, ItemType.BROKEN_RHYOLITE, ItemType.JADE_PICKAXES),
    DIORITE(14, 1000, 0, false, ItemType.BROKEN_DIORITE, ItemType.DIAMOND_PICKAXES),
    ANDESITE(15, 5000, 0, false, ItemType.BROKEN_ANDESITE, ItemType.DIAMOND_PICKAXES),*/
    BEDROCK(16, 10000000, 0, false, null, ItemType.NONE),

    // Drops from above
    BROKEN_TALC(17, 20, 0, false, ItemType.BROKEN_TALC, ItemType.ANY),
    BROKEN_GYPSUM(18, 40, 0, false, ItemType.BROKEN_GYPSUM, ItemType.ANY),
    BROKEN_CALCITE(19, 60, 0, false, ItemType.BROKEN_CALCITE, ItemType.ANY),
    BROKEN_LIMESTONE(20, 80, 0, false, ItemType.BROKEN_LIMESTONE, ItemType.ANY),
    BROKEN_SANDSTONE(21, 90, 0, false, ItemType.BROKEN_SANDSTONE, ItemType.ANY),
    BROKEN_MARBLE(22, 100, 0, false, ItemType.BROKEN_MARBLE, ItemType.ANY),
    BROKEN_APATITE(23, 120, 0, false, ItemType.BROKEN_APATITE, ItemType.ANY),
    BROKEN_BASALT(24, 140, 0, false, ItemType.BROKEN_BASALT, ItemType.ANY),
    BROKEN_OBSIDIAN(25, 150, 0, false, ItemType.BROKEN_OBSIDIAN, ItemType.ANY),
    BROKEN_FELDSPAR(26, 175, 0, false, ItemType.BROKEN_FELDSPAR, ItemType.ANY),
    BROKEN_PUMICE(27, 200, 0, false, ItemType.BROKEN_PUMICE, ItemType.ANY),
    BROKEN_GRANITE(28, 250, 0, false, ItemType.BROKEN_GRANITE, ItemType.ANY),
    BROKEN_RHYOLITE(29, 375, 0, false, ItemType.BROKEN_RHYOLITE, ItemType.ANY),
    BROKEN_DIORITE(30, 500, 0, false, ItemType.BROKEN_DIORITE, ItemType.ANY),
    BROKEN_ANDESITE(31, 1000, 0, false, ItemType.BROKEN_ANDESITE, ItemType.ANY),

    // Trees
    // - Real
    /*ALDER_LOG(),
    FRUIT_LOG(),
    ASH_LOG(),
    POPLAR_LOG(),
    BASSWOOD_LOG(),
    BIRCH_LOG(),
    BUCKEYE_LOG(),
    BUCKTHORN_LOG(),
    CATALPA_LOG(),
    CEDAR_LOG(),
    CHESTNUT_LOG(),
    CYPRESS_LOG(),
    DOGWOOD_LOG(),
    ELM_LOG(),
    FIR_LOG(),
    HAZEL_LOG(),
    SEQUOIA_LOG(),
    HOLLY_LOG(),
    JUNIPER_LOG(),
    MAPLE_LOG(),
    OAK_LOG(36, 20, 0, false, ItemType.OAK_LOG, ItemType.ANY),
    PINE_LOG(),
    REDWOOD_LOG(),
    SPRUCE_LOG(),
    WALNUT_LOG(),
    RUBBER_LOG(),
    // - Fantasy
    WHITE_DEWBERRY_LOG(),
    DEVILS_FUMEWORT_LOG(),
    ARROWWOOD_LOG(),
    SKUNKLEAF_LOG(),
    PLAGUEWOOD_LOG(),
    HEALING_ASH_LOG(),
    ORANGEROOT_LOG(),
    GREATWOOD_LOG(),
    IMPERIAL_LEAF_LOG(),
    PRANCING_PALM_LOG(),

    ALDER_PLANKS(),
    FRUIT_PLANKS(),
    ASH_PLANKS(),
    POPLAR_PLANKS(),
    BASSWOOD_PLANKS(),
    BIRCH_PLANKS(),
    BUCKEYE_PLANKS(),
    BUCKTHORN_PLANKS(),
    CATALPA_PLANKS(),
    CEDAR_PLANKS(),
    CHESTNUT_PLANKS(),
    CYPRESS_PLANKS(),
    DOGWOOD_PLANKS(),
    ELM_PLANKS(),
    FIR_PLANKS(),
    HAZEL_PLANKS(),
    SEQUOIA_PLANKS(),
    HOLLY_PLANKS(),
    JUNIPER_PLANKS(),
    MAPLE_PLANKS(),
    OAK_PLANKS(),
    PINE_PLANKS(),
    REDWOOD_PLANKS(),
    SPRUCE_PLANKS(),
    WALNUT_PLANKS(),
    RUBBER_PLANKS(),
    WHITE_DEWBERRY_PLANKS(),
    DEVILS_FUMEWORT_PLANKS(),
    ARROWWOOD_PLANKS(),
    SKUNKLEAF_PLANKS(),
    PLAGUEWOOD_PLANKS(),
    HEALING_ASH_PLANKS(),
    ORANGEROOT_PLANKS(),
    GREATWOOD_PLANKS(),
    IMPERIAL_LEAF_PLANKS(),
    PRANCING_PALM_PLANKS(),


    // Other natural generation
    DIRT(32, 5, 0, false, ItemType.DIRT, ItemType.SHOVELS),
    GRASS(33, 10, 0, false, ItemType.DIRT, ItemType.SHOVELS),
    GRAVEL(34, 20, 0, false, ItemType.GRAVEL, ItemType.SHOVELS),
    SAND(35, 5, 0, false, ItemType.SAND, ItemType.SHOVELS),
    LEAVES(37, 10, 0, false, null, ItemType.ANY),
    CLAY(38, 20, 0, false, ItemType.CLAY, ItemType.SHOVELS),
    LEYLINE(39, 10000000, 0, false, null, ItemType.NONE),
    ICE(),
    SNOW(),

    // Plants
    // - Real
    TALL_GRASS(),
    MYCELIUM(),
    LAVENDER(),
    BASIL(),
    DILL(),
    ROSEMARY(),
    OREGANO(),
    SPEARMINT(),
    SAGE(),
    HEMP(),
    NIGHTSHADE(),
    ALOE(),
    // - Fantasy
    GREAT_THISTLE(),
    DEAD_ROOT(),
    CAVE_TULIP(),
    TAUNTING_HEMP(),
    SOUR_MOSS(),
    SPIKY_ROOT(),
    DEMON_FLUXROOT(),
    ASHEN_BERRY(),
    ROYAL_WINTERBERRY(),
    IMP_LOTUS(),
    TUNDRA_CLOVE(),
    KNIGHTS_BRITTLEBUSH(),
    REGAL_FLOWER(),
    MAMMOTH_CAP(),
    DANCING_BINDWEED(),
    GREEN_HARLEQUIN(),
    SHADOW_FIG(),
    EEPHROLORN(),
    AROMATIC_PEPPER(),
    SPITFIRE_THIMBLEBERRY(),
    ASHEN_POISONBERRY(),
    POISONOUS_FELONWORT(),
    CAVE_ROOT(),

    // Crops - Mostly real
    RICE(),
    WHEAT(),
    SOYBEANS(),
    TOMATOES(),
    SUGARCANE(),
    MAIZE(),
    POTATOES(),
    GRAPES(),
    BERRIES(),
    COTTON(),
    APPLE_LEAVES(),
    SWEET_POTATOES(),
    BANANA_LEAVES(),
    MANGO_LEAVES(),
    COFFEE_BEANS(),
    ONIONS(),
    ALMONDS(),
    WALNUTS(),
    CHILIS(),
    PEPPERS(),
    RUBBER_WOOD(),
    TEA_LEAVES(),
    ORANGE_LEAVES(),
    CUCUMBERS(),
    PEACH_LEAVES(),
    LETTUCE(),
    CACAO_LEAVES(),
    SUNFLOWER(),
    WATERMELON(),
    ASPARAGUS(),
    CARROTS(),
    COCONUT_LEAVES(),
    TANGERINE_LEAVES(),
    LEMON_LEAVES(),
    LIME_LEAVES(),
    STRAWBERRIES(),
    PUMPKIN(),

    // Fungi - Mostly fantasy names
    ZELLERS_FOTT(),
    STAGS_HERICIUM(),
    ROCKMOSS_JELLY(),
    VELVET_CAP_DESTROYER(),
    VARIEGATED_MILKCAP(),
    MOSSY_MUSHROOMS(),
    TREMBLING_CAPS(),
    TUMBLE_BANE(),
    PURPLE_SPORED_AGARICUS(),
    WITCHS_PORIA(),
    BLUE_PRINCE(),
    ARTISTS_DOMECAP(),
    CANDY_JELLY(),
    BLACK_OYSTER(),
    INKY_LILLY(),
    FELT_FALSE_MOREL(),
    FRINGED_SHANKLET(),
    GILLED_TOP(),
    RIM_CLUSTERED_EAR_CUP(),
    WITCHS_ROCK_TRIPE(),

    // Liquids
    WATER(40, 100, 0, false, null, ItemType.NONE),
    LAVA(41, 100, 0, false, null, ItemType.NONE),
    OIL(42, 100, 0, false, null, ItemType.NONE),
    MERCURY(43, 100, 0, false, null, ItemType.NONE),

    // Ores
    ANTHITE(44, 200, 0, false, ItemType.BROKEN_ANTHITE, ItemType.IRON_PICKAXES),
    BARITE(45, 300, 0, false, ItemType.BROKEN_BARITE, ItemType.IRON_PICKAXES),
    BAUXITE(46, 200, 0, false, ItemType.BROKEN_BAUXITE, ItemType.IRON_PICKAXES),
    BERYL(47, 7500, 0, false, ItemType.BROKEN_BERYL, ItemType.DIAMOND_PICKAXES),
    BORNITE(48, 300, 0, false, ItemType.BROKEN_BORNITE, ItemType.IRON_PICKAXES),
    CASSITERITE(49, 5000, 0, false, ItemType.BROKEN_CASSITERITE, ItemType.DIAMOND_PICKAXES),
    CHALCOCITE(50, 300, 0, false, ItemType.BROKEN_CHALCOCITE, ItemType.IRON_PICKAXES),
    CHALCOPYRITE(51, 400, 0, false, ItemType.BROKEN_CHALCOPYRITE, ItemType.STONE_PICKAXES),
    CHROMITE(52, 1000, 0, false, ItemType.BROKEN_CHROMITE, ItemType.DIAMOND_PICKAXES),
    CINNABAR(53, 200, 0, false, ItemType.BROKEN_CINNABAR, ItemType.IRON_PICKAXES),
    COAL_ORE(54, 100, 0, false, ItemType.BROKEN_COAL_ORE, ItemType.STONE_PICKAXES),
    COBALTITE(55, 750, 0, false, ItemType.BROKEN_COBALTITE, ItemType.JADE_PICKAXES),
    COLTAN(56, 750, 0, false, ItemType.BROKEN_COLTAN, ItemType.JADE_PICKAXES),
    DOLOMITE(57, 400, 0, false, ItemType.BROKEN_DOLOMITE, ItemType.QUARTZ_PICKAXES),
    GALENA(58, 250, 0, false, ItemType.BROKEN_GALENA, ItemType.IRON_PICKAXES),
    GOLD_ORE(59, 275, 0, false, ItemType.BROKEN_GOLD_ORE, ItemType.IRON_PICKAXES),
    HEMATITE(60, 600, 0, false, ItemType.BROKEN_HEMATITE, ItemType.JADE_PICKAXES),
    ILMENITE(61, 850, 0, false, ItemType.BROKEN_ILMENITE, ItemType.JADE_PICKAXES),
    IRIDIUM_ORE(62, 1000, 0, false, ItemType.BROKEN_IRIDIUM_ORE, ItemType.DIAMOND_PICKAXES),
    MAGNETITE(63, 1250, 0, false, ItemType.BROKEN_MAGNETITE, ItemType.DIAMOND_PICKAXES),
    MALACHITE(64, 500, 0, false, ItemType.BROKEN_MALACHITE, ItemType.JADE_PICKAXES),
    MOLYBDENITE(65, 50, 0, false, ItemType.BROKEN_MOLYBDENITE, ItemType.STONE_PICKAXES),
    PENTLANDITE(66, 500, 0, false, ItemType.BROKEN_PENTLANDITE, ItemType.JADE_PICKAXES),
    PYROLUSITE(67, 1000, 0, false, ItemType.BROKEN_PYROLUSITE, ItemType.DIAMOND_PICKAXES),
    SCHEELITE(68, 750, 0, false, ItemType.BROKEN_SCHEELITE, ItemType.JADE_PICKAXES),
    SPERRYLITE(69, 2500, 0, false, ItemType.BROKEN_SPERRYLITE, ItemType.DIAMOND_PICKAXES),
    SPHALERITE(70, 500, 0, false, ItemType.BROKEN_SPHALERITE, ItemType.JADE_PICKAXES),
    URANINITE(71, 750, 0, false, ItemType.BROKEN_URANINITE, ItemType.JADE_PICKAXES),
    WOLFRAMITE(72, 500, 0, false, ItemType.BROKEN_WOLFRAMITE, ItemType.JADE_PICKAXES),

    // Drops from above
    BROKEN_ANTHITE(73, 20, 0, false, ItemType.BROKEN_ANTHITE, ItemType.ANY),
    BROKEN_BARITE(74, 30, 0, false, ItemType.BROKEN_BARITE, ItemType.ANY),
    BROKEN_BAUXITE(75, 20, 0, false, ItemType.BROKEN_BAUXITE, ItemType.ANY),
    BROKEN_BERYL(76, 750, 0, false, ItemType.BROKEN_BERYL, ItemType.ANY),
    BROKEN_BORNITE(77, 30, 0, false, ItemType.BROKEN_BORNITE, ItemType.ANY),
    BROKEN_CASSITERITE(78, 500, 0, false, ItemType.BROKEN_CASSITERITE, ItemType.ANY),
    BROKEN_CHALCOCITE(79, 30, 0, false, ItemType.BROKEN_CHALCOCITE, ItemType.ANY),
    BROKEN_CHALCOPYRITE(80, 40, 0, false, ItemType.BROKEN_CHALCOPYRITE, ItemType.ANY),
    BROKEN_CHROMITE(81, 100, 0, false, ItemType.BROKEN_CHROMITE, ItemType.ANY),
    BROKEN_CINNABAR(82, 20, 0, false, ItemType.BROKEN_CINNABAR, ItemType.ANY),
    BROKEN_COAL_ORE(83, 10, 0, false, ItemType.BROKEN_COAL_ORE, ItemType.ANY),
    BROKEN_COBALTITE(84, 75, 0, false, ItemType.BROKEN_COBALTITE, ItemType.ANY),
    BROKEN_COLTAN(85, 75, 0, false, ItemType.BROKEN_COLTAN, ItemType.ANY),
    BROKEN_DOLOMITE(86, 40, 0, false, ItemType.BROKEN_DOLOMITE, ItemType.ANY),
    BROKEN_GALENA(87, 25, 0, false, ItemType.BROKEN_GALENA, ItemType.ANY),
    BROKEN_GOLD_ORE(88, 28, 0, false, ItemType.BROKEN_GOLD_ORE, ItemType.ANY),
    BROKEN_HEMATITE(89, 60, 0, false, ItemType.BROKEN_HEMATITE, ItemType.ANY),
    BROKEN_ILMENITE(90, 85, 0, false, ItemType.BROKEN_ILMENITE, ItemType.ANY),
    BROKEN_IRIDIUM_ORE(91, 100, 0, false, ItemType.BROKEN_IRIDIUM_ORE, ItemType.ANY),
    BROKEN_MAGNETITE(92, 125, 0, false, ItemType.BROKEN_MAGNETITE, ItemType.ANY),
    BROKEN_MALACHITE(93, 50, 0, false, ItemType.BROKEN_MALACHITE, ItemType.ANY),
    BROKEN_MOLYBDENITE(94, 5, 0, false, ItemType.BROKEN_MOLYBDENITE, ItemType.ANY),
    BROKEN_PENTLANDITE(95, 50, 0, false, ItemType.BROKEN_PENTLANDITE, ItemType.ANY),
    BROKEN_PYROLUSITE(96, 100, 0, false, ItemType.BROKEN_PYROLUSITE, ItemType.ANY),
    BROKEN_SCHEELITE(97, 75, 0, false, ItemType.BROKEN_SCHEELITE, ItemType.ANY),
    BROKEN_SPERRYLITE(98, 250, 0, false, ItemType.BROKEN_SPERRYLITE, ItemType.ANY),
    BROKEN_SPHALERITE(99, 50, 0, false, ItemType.BROKEN_SPHALERITE, ItemType.ANY),
    BROKEN_URANINITE(100, 75, 0, false, ItemType.BROKEN_URANINITE, ItemType.ANY),
    BROKEN_WOLFRAMITE(101, 50, 0, false, ItemType.BROKEN_WOLFRAMITE, ItemType.ANY),

    // Purified metal blocks
    SILVER_BLOCK(102, 2000, 0, false, ItemType.SILVER_BLOCK, ItemType.QUARTZ_PICKAXES),
    SULFUR_BLOCK(103, 1500, 0, false, ItemType.SULFUR_BLOCK, ItemType.QUARTZ_PICKAXES),
    BARIUM_BLOCK(104, 2000, 0, false, ItemType.BARIUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    ALUMINUM_BLOCK(105, 1500, 0, false, ItemType.ALUMINUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    BERYLLIUM_BLOCK(106, 10000, 0, false, ItemType.BERYLLIUM_BLOCK, ItemType.JADE_PICKAXES),
    SILICON_BLOCK(107, 1500, 0, false, ItemType.SILICON_BLOCK, ItemType.QUARTZ_PICKAXES),
    COPPER_BLOCK(108, 5000, 0, false, ItemType.COPPER_BLOCK, ItemType.QUARTZ_PICKAXES),
    IRON_BLOCK(109, 15000, 0, false, ItemType.IRON_BLOCK, ItemType.JADE_PICKAXES),
    TIN_BLOCK(110, 5000, 0, false, ItemType.TIN_BLOCK, ItemType.QUARTZ_PICKAXES),
    CHROMIUM_BLOCK(111, 2500, 0, false, ItemType.CHROMIUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    MAGNESIUM_BLOCK(112, 1000, 0, false, ItemType.MAGNESIUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    COBALT_BLOCK(113, 12500, 0, false, ItemType.COBALT_BLOCK, ItemType.JADE_PICKAXES),
    ARSENIC_BLOCK(114, 1000, 0, false, ItemType.ARSENIC_BLOCK, ItemType.QUARTZ_PICKAXES),
    MANGANESE_BLOCK(115, 1000, 0, false, ItemType.MANGANESE_BLOCK, ItemType.QUARTZ_PICKAXES),
    NIOBIUM_BLOCK(116, 2000, 0, false, ItemType.NIOBIUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    TANTALUM_BLOCK(117, 2500, 0, false, ItemType.TANTALUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    LEAD_BLOCK(118, 1250, 0, false, ItemType.LEAD_BLOCK, ItemType.QUARTZ_PICKAXES),
    GOLD_BLOCK(119, 1000, 0, false, ItemType.GOLD_BLOCK, ItemType.QUARTZ_PICKAXES),
    TITANIUM_BLOCK(120, 50000, 0, false, ItemType.TITANIUM_BLOCK, ItemType.DIAMOND_PICKAXES),
    IRIDIUM_BLOCK(121, 15000, 0, false, ItemType.IRIDIUM_BLOCK, ItemType.DIAMOND_PICKAXES),
    MOLYBDENUM_BLOCK(122, 1000, 0, false, ItemType.MOLYBDENUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    NICKEL_BLOCK(123, 2500, 0, false, ItemType.NICKEL_BLOCK, ItemType.QUARTZ_PICKAXES),
    CALCIUM_BLOCK(124, 1000, 0, false, ItemType.CALCIUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    TUNGSTEN_BLOCK(125, 75000, 0, false, ItemType.TUNGSTEN_BLOCK, ItemType.DIAMOND_PICKAXES),
    PLATINUM_BLOCK(126, 15000, 0, false, ItemType.PLATINUM_BLOCK, ItemType.DIAMOND_PICKAXES),
    ZINC_BLOCK(127, 1500, 0, false, ItemType.ZINC_BLOCK, ItemType.QUARTZ_PICKAXES),
    URANIUM_BLOCK(128, 3500, 0, false, ItemType.URANIUM_BLOCK, ItemType.QUARTZ_PICKAXES),
    COAL_BLOCK(129, 1000, 0, false, ItemType.COAL_BLOCK, ItemType.QUARTZ_PICKAXES),

    // Gemstones
    ALEXANDRITE_ORE(130, 800, 0, false, ItemType.ALEXANDRITE_GEM, ItemType.QUARTZ_PICKAXES),
    AMETHYST_ORE(131, 1000, 0, false, ItemType.AMETHYST_GEM, ItemType.JADE_PICKAXES),
    AQUAMARINE_ORE(132, 600, 0, false, ItemType.AQUAMARINE_GEM, ItemType.QUARTZ_PICKAXES),
    CITRINE_ORE(133, 900, 0, false, ItemType.CITRINE_GEM, ItemType.QUARTZ_PICKAXES),
    DIAMOND_ORE(134, 10000, 0, false, ItemType.DIAMOND_GEM, ItemType.JADE_PICKAXES),
    EMERALD_ORE(135, 600, 0, false, ItemType.EMERALD_GEM, ItemType.JADE_PICKAXES),
    GARNET_ORE(136, 500, 0, false, ItemType.GARNET_GEM, ItemType.QUARTZ_PICKAXES),
    JADE_ORE(137, 2000, 0, false, ItemType.JADE_GEM, ItemType.QUARTZ_PICKAXES),
    LAPIS_LAZULI_ORE(138, 200, 0, false, ItemType.LAPIS_LAZULI_GEM, ItemType.QUARTZ_PICKAXES),
    MOONSTONE_ORE(139, 1000, 0, false, ItemType.MOONSTONE_GEM, ItemType.JADE_PICKAXES),
    MORGANITE_ORE(140, 600, 0, false, ItemType.MORGANITE_GEM, ItemType.JADE_PICKAXES),
    ONYX_ORE(141, 500, 0, false, ItemType.ONYX_GEM, ItemType.QUARTZ_PICKAXES),
    OPAL_ORE(142, 800, 0, false, ItemType.OPAL_GEM, ItemType.JADE_PICKAXES),
    PEARL_ORE(143, 600, 0, false, ItemType.PEARL_GEM, ItemType.JADE_PICKAXES),
    PERIDOT_ORE(144, 200, 0, false, ItemType.PERIDOT_GEM, ItemType.QUARTZ_PICKAXES),
    RUBELLITE_ORE(145, 400, 0, false, ItemType.RUBELLITE_GEM, ItemType.QUARTZ_PICKAXES),
    RUBY_ORE(146, 600, 0, false, ItemType.RUBY_GEM, ItemType.JADE_PICKAXES),
    SAPPHIRE_ORE(147, 1000, 0, false, ItemType.SAPPHIRE_GEM, ItemType.JADE_PICKAXES),
    SPINEL_ORE(148, 600, 0, false, ItemType.SPINEL_GEM, ItemType.JADE_PICKAXES),
    SUNSTONE_ORE(),
    TANZANITE_ORE(149, 700, 0, false, ItemType.TANZANITE_GEM, ItemType.JADE_PICKAXES),
    TOPAZ_ORE(150, 1200, 0, false, ItemType.TOPAZ_GEM, ItemType.JADE_PICKAXES),
    TOURMALINE_ORE(151, 500, 0, false, ItemType.TOURMALINE_GEM, ItemType.QUARTZ_PICKAXES),
    TURQUOISE_ORE(152, 300, 0, false, ItemType.TURQUOISE_GEM, ItemType.QUARTZ_PICKAXES),
    QUARTZ_ORE(153, 2900, 0, false, ItemType.QUARTZ_GEM, ItemType.IRON_PICKAXES),
    ZIRCON_ORE(154, 1000, 0, false, ItemType.ZIRCON_GEM, ItemType.JADE_PICKAXES),

    // Polished gemstone blocks
    ALEXANDRITE_BLOCK(155, 8000, 0, false, ItemType.ALEXANDRITE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    AMETHYST_BLOCK(156, 10000, 0, false, ItemType.AMETHYST_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    AQUAMARINE_BLOCK(157, 6000, 0, false, ItemType.AQUAMARINE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    CITRINE_BLOCK(158, 9000, 0, false, ItemType.CITRINE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    DIAMOND_BLOCK(159, 100000, 0, false, ItemType.DIAMOND_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    EMERALD_BLOCK(160, 6000, 0, false, ItemType.EMERALD_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    GARNET_BLOCK(161, 5000, 0, false, ItemType.GARNET_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    JADE_BLOCK(162, 20000, 0, false, ItemType.JADE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    LAPIS_LAZULI_BLOCK(163, 2000, 0, false, ItemType.LAPIS_LAZULI_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    MOONSTONE_BLOCK(164, 10000, 0, false, ItemType.MOONSTONE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    MORGANITE_BLOCK(165, 6000, 0, false, ItemType.MORGANITE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    ONYX_BLOCK(166, 5000, 0, false, ItemType.ONYX_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    OPAL_BLOCK(167, 8000, 0, false, ItemType.OPAL_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    PEARL_BLOCK(168, 6000, 0, false, ItemType.PEARL_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    PERIDOT_BLOCK(169, 2000, 0, false, ItemType.PERIDOT_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    RUBELLITE_BLOCK(170, 4000, 0, false, ItemType.RUBELLITE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    RUBY_BLOCK(171, 6000, 0, false, ItemType.RUBY_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    SAPPHIRE_BLOCK(172, 10000, 0, false, ItemType.SAPPHIRE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    SPINEL_BLOCK(173, 6000, 0, false, ItemType.SPINEL_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    SUNSTONE_BLOCK(),
    TANZANITE_BLOCK(174, 7000, 0, false, ItemType.TANZANITE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    TOPAZ_BLOCK(175, 12000, 0, false, ItemType.TOPAZ_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    TOURMALINE_BLOCK(176, 5000, 0, false, ItemType.TOURMALINE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    TURQUOISE_BLOCK(177, 3000, 0, false, ItemType.TURQUOISE_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    QUARTZ_BLOCK(178, 29000, 0, false, ItemType.QUARTZ_BLOCK, ItemType.TUNGSTEN_PICKAXES),
    ZIRCON_BLOCK(179, 10000, 0, false, ItemType.ZIRCON_BLOCK, ItemType.TUNGSTEN_PICKAXES),

    // Craftables
    PLANKS(180, 100, 0, false, null, null),
    STAIRS(181, 100, 0, false, null, null),
    FENCE(182, 100, 0, true, null, null),
    LADDER(183, 100, 0, true, null, null),
    WOODEN_SLAB(184, 100, 0, true, null, null),
    DOOR(185, 100, 0, false, null, null),
    BRICKS(),

    // Light
    TORCH(),
    LAMP(),
    JACKOLANTERN(),
    FLOODLIGHT(),
    ARCANE_LIGHT(),

    // Storage
    WOODEN_CHEST(186, 100, 0, false, null, null),
    STONE_CHEST(187, 100, 0, false, null, null),
    DIAMOND_CHEST(188, 100, 0, false, null, null),
    RUBY_CHEST(189, 100, 0, false, null, null),
    SAPPHIRE_CHEST(190, 100, 0, false, null, null),
    TITANIUM_CHEST(191, 100, 0, false, null, null),
    TUNGSTEN_CHEST(192, 100, 0, false, null, null),
    WOODEN_BOWL(193, 100, 0, false, null, null),
    STONE_TANK(194, 100, 0, false, null, null),
    DIAMOND_TANK(195, 100, 0, false, null, null),
    RUBY_TANK(196, 100, 0, false, null, null),
    SAPPHIRE_TANK(197, 100, 0, false, null, null),
    TITANIUM_TANK(198, 100, 0, false, null, null),
    TUNGSTEN_TANK(199, 100, 0, false, null, null),

    // Logistics
    ITEM_PIPE(203, 100, 0, false, null, null),
    LIQUID_PIPE(204, 100, 0, false, null, null),
    VACUUM_PIPE(205, 100, 0, false, null, null),

    // Machines
    CRAFTING_TABLE(209, 100, 0, false, null, null),

    // Heat
    HEAT_PIPE(),
    COMBUSTION_FURNACE(),
    ELECTRIC_FURNACE(),
    OVEN(207, 100, 0, false, null, null),
    REFINERY(219, 100, 0, false, null, null),

    // Steam
    BOILER(),
    HEAT_EXCHANGER(),
    STEAM_ENGINE(),

    // Etheric
    LESSER_ETHERIC_BATTERY(),
    GREATER_ETHERIC_BATTERY(),
    IMMENSE_ETHERIC_BATTERY(),
    ETHER_PIPE(206, 100, 0, false, null, null),
    TESSERACT(228, 100, 0, false, null, null),
    TELEPORTER(229, 100, 0, false, null, null),
    LEYLINE_ETHER_TAP(230, 100, 0, false, null, null),

    // Pneumatics
    COMBUSTION_ENGINE(200, 100, 0, false, null, null),
    ELECTRIC_ENGINE(201, 100, 0, false, null, null),
    ETHERIC_ENGINE(202, 100, 0, false, null, null),
    PNEUMATIC_PIPE(),
    PUMP(224, 100, 0, false, null, null),
    GRINDER(208, 100, 0, false, null, null),
    COIN_PRESS(211, 100, 0, false, null, null),
    PISTON(221, 100, 0, false, null, null),
    QUARRY(223, 100, 0, false, null, null),
    MILL(231, 100, 0, false, null, null),

    // Electricity
    TIN_WIRE(),
    ALUMINUM_WIRE(),
    COPPER_WIRE(),
    TUNGSTEN_WIRE(),
    LOW_VOLTAGE_TRANSFORMER(),
    MEDIUM_VOLTAGE_TRANSFORMER(),
    HIGH_VOLTAGE_TRANSFORMER(),
    EXTREME_VOLTAGE_TRANSFORMER(),
    LEAD_BATTERY(),
    NICKEL_BATTERY(),
    FLUX_BATTERY(),
    BASIC_CAPACITOR(),
    SUPER_CAPACITOR(),
    SOLAR_PANEL(218, 100, 0, false, null, null),
    COAL_GENERATOR(216, 100, 0, false, null, null),
    PNEUMATIC_GENERATOR(217, 100, 0, false, null, null),
    THERMOELECTRIC_GENERATOR(),
    AUTOMATED_CRAFTING_TABLE(210, 100, 0, false, null, null),
    AUTOMATED_FARMING_UNIT(220, 100, 0, false, null, null),
    SHIELD(222, 100, 0, false, null, null),

    // Circuits
    CIRCUIT_DESIGNER(213, 100, 0, false, null, null),
    INTEGRATED_CIRCUIT(214, 100, 0, false, null, null),
    CIRCUIT_WIRE(215, 100, 0, false, null, null),
    SWITCH(),
    PRESSURE_PLATE(),
    LIGHT_SENSOR(),
    LOW_VOLTAGE_RECTIFIER(),

    // Computers
    MICRO_CONTROLLER(),
    DIGITAL_WIRE(),
    DATA_STORAGE_UNIT(),
    ANALOG_DIGITAL_CONVERTER(),
    DIGITAL_ANALOG_CONVERTER(),
    DISPLAY(),
    DIGITAL_MARKET_ADAPTER(225, 100, 0, false, null, null),
    DIGITAL_BANK_ADAPTER(226, 100, 0, false, null, null),
    STORAGE_ADAPTER(),
    PROGRAMMER(),
    RADIO_TRANSCEIVER(),

    // Digital Storage
    STORAGE_COMPUTER(212, 100, 0, false, null, null),
    WIRELESS_STORAGE_BASE_STATION(227, 100, 0, false, null, null),
    SIMPLE_STORAGE_BUS(),
    MULTIPLEXED_STORAGE_BUS(),
    MATTER_DIGITAL_CONVERTER(),
    DIGITAL_MATTER_CONVERTER(),
    PHYSICAL_STORAGE_INTERFACE(),
    MULTIPLEXER(),
    DIGIMECHANICAL_HANDLER(),
    HIGH_VOLTAGE_RECTIFIER(),
    BASIC_STORAGE_BUILDING_BLOCK(),
    ADVANCED_STORAGE_BUILDING_BLOCK(),
    STORAGE_TERMINAL(),

    // Decorative
    WOOL(),
    CONCRETE(),
    CEMENT(),
    PACKED_CLAY(),
    PACKED_DIRT(),
    MASONRY(),
    CHAIR(),
    TABLE(),
    WINDOW(),
    SIGN(),
    PAINTING(),
    JUKEBOX(),
    GLASS(),
    GLASS_PANE(),
    ITEM_FRAME(),
    BED(),
    CARPET(),
    CAMP_FIRE(),
    FLOWER_POT()*/
    ;

    private static final Map<Integer, BlockType> map = new HashMap<>();

    static {
        for(final BlockType blockType : values()) {
            if(map.containsKey(blockType.id))
                throw new IllegalStateException();
            map.put(blockType.id, blockType);
        }
    }

    @JsonCreator
    public static BlockType fromId(final int id) {
        return map.get(id);
    }

    private final int id;
    private final int hardness;
    private final int lightProduced;
    private final boolean transparent;
    private final ItemType breakItem;
    private final ItemType[] breakableBy;

    BlockType(final int id, final int hardness, final int lightProduced, final boolean transparent,
              final ItemType breakItem, final ItemType[] breakableBy) {
        this.id = id;
        this.hardness = hardness;
        this.lightProduced = lightProduced;
        this.transparent = transparent;
        this.breakItem = breakItem;
        this.breakableBy = breakableBy;
    }

    @JsonValue
    public int toValue() {
        return id;
    }

    public boolean isTransparent() {
        return transparent;
    }
}
