package com.runetide.common.domain;

public enum RuneType {
    CAST, DEATH, PERSIST, PROXIMITY, DAMAGE,

    COMBINING,

    SELF, TOUCH, RANGE, BOUND,

    DISTANCE,

    LINE, CONE, AREA,

    SPHERE, COLUMN, CUBE,

    CLOSE, FAR, CENTER,

    EFFECT, HEALING, DIG, TELEPORT, BIND,

    DURATION,

    EYES, LANGUAGE, JUMPING, SPEED, SLOW, CHARM, LIGHT,

    FIRE, COLD, NECROTIC, RADIANT, LIGHTNING, SONIC, NATURE, PSYCHIC, POISON, ACID, ARCANE, DARK,

    POWER;
}
