package com.runetide.services.internal.character.common;

public enum EquipmentSlot {
    HEAD, CHEST, LEGS, FEET, HANDS, FINGER_0, FINGER_1, FINGER_2, FINGER_3, FINGER_4, FINGER_5, FINGER_6, FINGER_7,
    AMULET, TRINKET_0, TRINKET_1, NECK, WRIST, WAIST, SHOULDERS, BACKPACK, MAIN_HAND, OFF_HAND, HOTBAR_0, HOTBAR_1,
    HOTBAR_2, HOTBAR_3, HOTBAR_4, HOTBAR_5, HOTBAR_6, HOTBAR_7, HOTBAR_8, HOTBAR_9
}
