package com.runetide.services.internal.region.common;

import com.fasterxml.jackson.annotation.JsonValue;

public enum BlockType {
    AIR,

    TALC, GYPSUM, CALCITE, LIMESTONE, SANDSTONE, MARBLE, APATITE, BASALT, OBSIDIAN, FELDSPAR, PUMICE, GRANITE, RHYOLITE,
    DIORITE, ANDESITE, BEDROCK,

    BROKEN_TALC, BROKEN_GYPSUM, BROKEN_CALCITE, BROKEN_LIMESTONE, BROKEN_SANDSTONE, BROKEN_MARBLE, BROKEN_APATITE,
    BROKEN_BASALT, BROKEN_OBSIDIAN, BROKEN_FELDSPAR, BROKEN_PUMICE, BROKEN_GRANITE, BROKEN_RHYOLITE, BROKEN_DIORITE,
    BROKEN_ANDESITE,

    DIRT, GRASS, GRAVEL, SAND, LOG, LEAVES, CLAY, LEYLINE,

    WATER, LAVA, OIL, MERCURY,

    ANTHITE, BARITE, BAUXITE, BERYL, BORNITE, CASSITERITE, CHALCOCITE, CHALCOPYRITE, CHROMITE, CINNABAR, COAL_ORE,
    COBALTITE, COLTAN, DOLOMITE, GALENA, GOLD_ORE, HEMATITE, ILMENITE, IRIDIUM_ORE, MAGNETITE, MALACHITE, MOLYBDENITE,
    PENTLANDITE, PYROLUSITE, SCHEELITE, SPERRYLITE, SPHALERITE, URANINITE, WOLFRAMITE,

    BROKEN_ANTHITE, BROKEN_BARITE, BROKEN_BAUXITE, BROKEN_BERYL, BROKEN_BORNITE, BROKEN_CASSITERITE, BROKEN_CHALCOCITE,
    BROKEN_CHALCOPYRITE, BROKEN_CHROMITE, BROKEN_CINNABAR, BROKEN_COAL_ORE, BROKEN_COBALTITE, BROKEN_COLTAN,
    BROKEN_DOLOMITE, BROKEN_GALENA, BROKEN_GOLD_ORE, BROKEN_HEMATITE, BROKEN_ILMENITE, BROKEN_IRIDIUM_ORE,
    BROKEN_MAGNETITE, BROKEN_MALACHITE, BROKEN_MOLYBDENITE, BROKEN_PENTLANDITE, BROKEN_PYROLUSITE, BROKEN_SCHEELITE,
    BROKEN_SPERRYLITE, BROKEN_SPHALERITE, BROKEN_URANINITE, BROKEN_WOLFRAMITE,

    SILVER_BLOCK, SULFUR_BLOCK, BARIUM_BLOCK, ALUMINUM_BLOCK, BERYLLIUM_BLOCK, SILICON_BLOCK, COPPER_BLOCK, IRON_BLOCK,
    TIN_BLOCK, CHROMIUM_BLOCK, MAGNESIUM_BLOCK, COBALT_BLOCK, ARSENIC_BLOCK, MANGANESE_BLOCK, NIOBIUM_BLOCK,
    TANTALUM_BLOCK, LEAD_BLOCK, GOLD_BLOCK, TITANIUM_BLOCK, IRIDIUM_BLOCK, MOLYBDENUM_BLOCK, NICKEL_BLOCK,
    CALCIUM_BLOCK, TUNGSTEN_BLOCK, PLATINUM_BLOCK, ZINC_BLOCK, URANIUM_BLOCK, COAL_BLOCK,

    ALEXANDRITE_ORE, AMETHYST_ORE, AQUAMARINE_ORE, CITRINE_ORE, DIAMOND_ORE, EMERALD_ORE, GARNET_ORE, JADE_ORE,
    LAPIS_LAZULI_ORE, MOONSTONE_ORE, MORGANITE_ORE, ONYX_ORE, OPAL_ORE, PEARL_ORE, PERIDOT_ORE, RUBELLITE_ORE, RUBY_ORE,
    SAPPHIRE_ORE, SPINEL_ORE, TANZANITE_ORE, TOPAZ_ORE, TOURMALINE_ORE, TURQUOISE_ORE, QUARTZ_ORE, ZIRCON_ORE,

    ALEXANDRITE_BLOCK, AMETHYST_BLOCK, AQUAMARINE_BLOCK, CITRINE_BLOCK, DIAMOND_BLOCK, EMERALD_BLOCK, GARNET_BLOCK,
    JADE_BLOCK, LAPIS_LAZULI_BLOCK, MOONSTONE_BLOCK, MORGANITE_BLOCK, ONYX_BLOCK, OPAL_BLOCK, PEARL_BLOCK,
    PERIDOT_BLOCK, RUBELLITE_BLOCK, RUBY_BLOCK, SAPPHIRE_BLOCK, SPINEL_BLOCK, TANZANITE_BLOCK, TOPAZ_BLOCK,
    TOURMALINE_BLOCK, TURQUOISE_BLOCK, QUARTZ_BLOCK, ZIRCON_BLOCK,

    PLANKS, STAIRS, FENCE, LADDER, WOODEN_SLAB, DOOR,

    WOODEN_CHEST, STONE_CHEST, DIAMOND_CHEST, RUBY_CHEST, SAPPHIRE_CHEST, TITANIUM_CHEST, TUNGSTEN_CHEST,
    WOODEN_BOWL, STONE_TANK, DIAMOND_TANK, RUBY_TANK, SAPPHIRE_TANK, TITANIUM_TANK, TUNGSTEN_TANK,
    COMBUSTION_ENGINE, ELECTRIC_ENGINE, ETHERIC_ENGINE,
    ITEM_PIPE, LIQUID_PIPE, VACUUM_PIPE, ETHER_PIPE,

    FURNACE, GRINDER, CRAFTING_TABLE, AUTOMATED_CRAFTING_TABLE, COIN_PRESS, STORAGE_COMPUTER, CIRCUIT_DESIGNER,
    INTEGRATED_CIRCUIT, CIRCUIT_WIRE, COAL_GENERATOR, PNEUMATIC_GENERATOR, SOLAR_PANEL, REFINERY,
    AUTOMATED_FARMING_UNIT, PISTON, SHIELD, QUARRY, PUMP, DIGITAL_MARKET_ADAPTER, DIGITAL_BANK_ADAPTER,
    WIRELESS_STORAGE_DEVICE, TESSERACT, TELEPORTER, LEYLINE_ETHER_TAP;

    @JsonValue
    public int toValue() {
        return ordinal();
    }
}
